### ISSUE TITLE
Can I remove Contact from LaminSanneh.com? and how?

### ISSUE THREAD

**Issue by kdon80** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#23]
Can I remove LaminSanneh.com from the email title?? If yes, can I overwrite it so I don't have to touch the plugin file?

This is where it's at:
/flexicontact/views/emails/message.htm

thanks,

**Comment by LaminSanneh** [comment]
Yes thats is just a default template.
You can modify it in the backend.
When modified, the one in the backend will be used instead of the default one that comes with teh plugin as the backend templates are stored in the database so you arent modifying the plugin file itself.
make sense?
The docs here explain mor ein detail http://octobercms.com/docs/services/mail#mail-templates

**Comment by kdon80** [comment]
uhhhhhh. Super! Makes sense. Thanks!
