### ISSUE TITLE
Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by jbh** [LaminSanneh/Octobercms-Flexi-Contact-Plugin#7]
I keep getting this error when submitting the form. It holds up the ajax call due to the JS error, so it never finishes loading.

The form works and sends the email, which is great, but the user continues to see the form as loading until the page is reloaded. The error has to do with:

```coffeescript
$('.flexiContactForm').on 'ajaxSuccess', (ev, context, data, status, jqXHR) ->
  if data.error is true
    console.log(arguments)
  else
    $('.form-groups').hide(1000)
```

It is saying that data is undefined, which is weird. I haven't done any customization yet. This is how it is working right out of the box. It's also getting a 404 error for the main.coffee file, which is also strange because it is in the same folder as main.js, and it finds that fine.

**Comment by jbh-** [comment]
Here are screenshots that may give more helpful information. For the time being, I removed the source mapping since that was causing the 404. It still says `data` is undefined, though. In the following screenshot, one can see that it is clearly defined within the `arguments` object.

![errors-2015-03-17_09-50-39](https://cloud.githubusercontent.com/assets/5510679/6689991/9bdd7dde-cc8b-11e4-972d-b98dd2bbee2c.png)

It's like it is being called twice, and the second time it only has the event object. I added a console log of the arguments, and it looks like the function is being called 4 times, and 2 times the object is not defined.

![even-more-2015-03-17_09-57-36](https://cloud.githubusercontent.com/assets/5510679/6690068/14c5fc12-cc8c-11e4-81b3-a59e27adf72c.png)

**Comment by scottstone72** [comment]
Ever find a solution? Today I have the same problem.

**Comment by LaminSanneh** [comment]
Does this issue still persist. Closing for now until asked to reopen.

**Comment by nozreh** [comment]
This error still exists, error in the main.coffee
`main.coffee:2 Uncaught TypeError: Cannot read property 'error' of undefined
    at HTMLFormElement.<anonymous> (main.coffee:2)`
